### PR TITLE
dynamic datatable based on column selected

### PR DESCRIPTION
**Pull request by fuzheng1998**
- column can be selected and deselected
- data may not sync to display at the same time

### CODE REVIEW

**Comment by fuzheng1998** [comment]
all problems resolved @kovarny

**Review by kovarny — COMMENTED** [review]
can we  see it in your branch at some point?

**Comment by fuzheng1998** [comment]
> can we see it in your branch at some point?

i will be in meeting tomorrow morning

**Review by kovarny — APPROVED** [review]
lgtm

**Pull request merged**
